### ISSUE TITLE
more info on the list page would be useful

### ISSUE THREAD

**Issue by mattlub** [FACN1/VolunteerApp#21]
As someone looking to volunteer I think I would be interested in seeing the location and dates of the role on the listings page.

**Comment by HilbertSpitzer** [comment]
Yes, perhaps some want an organization close to their home, perhaps some people are too busy and aren't always available at the same times and want flexibility, perhaps some people don't have the strength/ability to do certain things and want to make sure that the organization that they picked also fits in better with their needs
